export const registroRoutes = [
  {
    key: "compras",
    grupo: "Entradas",
    titulo: "Registro de Compras",
    descripcion: "Listado principal de compras directas y sus revisiones.",
    route: "/private/page/transacciones/compra/vista",
    origenes: [
      "src/app/private/page/transacciones/compra/page.js",
      "src/app/private/page/transacciones/venta/page.js",
    ],
  },
  {
    key: "depositos",
    grupo: "Entradas",
    titulo: "Registro de Depositos",
    descripcion: "Consulta general de depositos registrados por cliente.",
    route: "/private/page/informe/registrodeposito",
    origenes: ["src/app/private/page/transacciones/deposito/page.js"],
  },
  {
    key: "liq-depositos",
    grupo: "Entradas",
    titulo: "Registro de Liquidaciones de Deposito",
    descripcion: "Revision de liquidaciones asociadas a depositos.",
    route: "/private/page/transacciones/deposito/lipdedeposito",
    origenes: [
      "src/app/private/page/transacciones/deposito/liqDeposito/page.js",
      "src/app/private/page/informe/registrodeposito/page.js",
    ],
  },
  {
    key: "contratos-entrada",
    grupo: "Entradas",
    titulo: "Registro de Contratos de Entrada",
    descripcion: "Listado de contratos de compra y su estado.",
    route: "/private/page/transacciones/contrato/registrocontrato",
    origenes: ["src/app/private/page/transacciones/contrato/page.js"],
  },
  {
    key: "entregas-entrada",
    grupo: "Entradas",
    titulo: "Registro de Entregas de Contrato",
    descripcion: "Detalle de entregas relacionadas a contratos de entrada.",
    route: "/private/page/transacciones/contrato/detallecontrato",
    origenes: [
      "src/app/private/page/transacciones/contrato/page.js",
      "src/app/private/page/transacciones/contrato/entrega/page.js",
      "src/app/private/page/transacciones/contrato/registrocontrato/page.js",
    ],
  },
  {
    key: "confirmaciones-salida",
    grupo: "Salidas",
    titulo: "Registro de Confirmaciones de Salida",
    descripcion: "Revision de compromisos y confirmaciones de salida.",
    route: "/private/page/transacciones/salidas/registro",
    origenes: ["src/app/private/page/transacciones/salidas/page.js"],
  },
  {
    key: "liq-salidas",
    grupo: "Salidas",
    titulo: "Registro de Liquidaciones de Salida",
    descripcion: "Listado de liquidaciones generadas para salidas.",
    route: "/private/page/transacciones/salidas/registroliq",
    origenes: [
      "src/app/private/page/transacciones/salidas/page.js",
      "src/app/private/page/transacciones/salidas/registro/page.js",
    ],
  },
  {
    key: "contratos-salida",
    grupo: "Salidas",
    titulo: "Registro de Contratos de Salida",
    descripcion: "Consulta general de contratos de venta por comprador.",
    route: "/private/page/transacciones/contratoSalida/registrocontrato",
    origenes: [
      "src/app/private/page/transacciones/contratoSalida/page.js",
      "src/app/private/page/transacciones/venta/page.js",
    ],
  },
  {
    key: "entregas-salida",
    grupo: "Salidas",
    titulo: "Registro de Entregas de Contrato de Salida",
    descripcion: "Detalle de entregas vinculadas a contratos de salida.",
    route: "/private/page/transacciones/contratoSalida/detallecontrato",
    origenes: [
      "src/app/private/page/transacciones/contratoSalida/entrega/page.js",
      "src/app/private/page/transacciones/contratoSalida/registrocontrato/page.js",
    ],
  },
  {
    key: "prestamos-clientes",
    grupo: "Entradas",
    titulo: "Registro de Prestamos y Anticipos",
    descripcion: "Estado de cuenta de prestamos y anticipos por cliente.",
    route: "/private/page/transacciones/prestamos",
    origenes: ["src/app/private/page/transacciones/prestamos/page.js"],
  },
  {
    key: "prestamos-compradores",
    grupo: "Salidas",
    titulo: "Registro de Prestamos y Anticipos de Compradores",
    descripcion: "Estado de cuenta de prestamos y anticipos por comprador.",
    route: "/private/page/transacciones/prestamosCompradores",
    origenes: [
      "src/app/private/page/transacciones/prestamosCompradores/page.js",
    ],
  },
  {
    key: "secado",
    grupo: "Entradas",
    titulo: "Registro de Secado",
    descripcion: "Reporte de lotes en proceso de secado y su estado.",
    route: "/private/page/secado/reporte",
    origenes: ["src/app/private/page/secado/page.js"],
  },
];
